### ISSUE TITLE
Receiving Error

### ISSUE THREAD

**Issue by satrox28** [wongherlung/static_pokemon_go_alert#1]
Traceback (most recent call last):
  File "poke_map.py", line 78, in <module>
    main();
  File "poke_map.py", line 16, in main
    pokemons = getDataFromSGPokeMap()["pokemons"]
  File "poke_map.py", line 52, in getDataFromSGPokeMap
    r = s.get("https://sgpokemap.com/query2.php?since="+str(current_epoch_time)+"&mons=1,2,3,4,5,6,7,8,9,25,26,29,30,31,32,33,34,35,36,37,38,40,42,44,45,50,51,55,56,57,58,59,61,62,63,64,65,66,67,68,70,71,74,75,76,78,79,80,83,86,87,88,89,90,91,92,93,94,95,96,97,103,105,106,107,108,109,110,111,112,113,115,117,122,123,124,128,130,131,132,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151")
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python2.7/httplib.py", line 1030, in putheader
    raise ValueError('Invalid header name %r' % (header,))
ValueError: Invalid header name ':authority'

is it still working?. i am receiving the above error.

**Comment by wongherlung** [comment]
Yes. It should still be working. I'll help you out with this in a bit.

**Comment by satrox28** [comment]
Can you test and let me know

**Comment by wongherlung** [comment]
@satrox28 can you try now? pushed a fix, see if it works for you.

**Comment by satrox28** [comment]
{u'defence': u'6', u'pokemon_id': u'123', u'stamina': u'5', u'attack': u'12', u'lat': u'1.4201671', u'move1': u'200', u'lng': u'103.84042019', u'move2': u'49', u'despawn': u'1483074646'}
{u'defence': u'13', u'pokemon_id': u'74', u'stamina': u'11', u'attack': u'14', u'lat': u'1.42032321', u'move1': u'221', u'lng': u'103.83888034', u'move2': u'63', u'despawn': u'1483073962'}
2016-12-30 12:51:15.139 GSSpeechServer[19191:19191] No handle for event rport on descriptor 14

i am getting like this. will it not show cords for all pokemon?. and does it show the name.

i am using the default files config.

**Comment by wongherlung** [comment]
@satrox28 The whole idea of this app is to only **verbalise** what pokemon is around a given location (your home for eg) for a given radius. You'll have to edit the values for `current_lat_lng ` and `detection_radius ` in the first few lines of the `poke_map.py file`.

The json response you got above tells me that it should be working fine. Make sure you run this: `sudo apt-get install gnustep-gui-runtime` and restart your system for good measure.

**Comment by satrox28** [comment]
I have installed the gnustep-gui-runtime, oh ok i thought it can extract all cords from the map with some filters.

**Comment by wongherlung** [comment]
Can be done. You'll just have to edit it to suit your purposes. :)
